backend:
  autoscaling:
    enabled: false
  enabled: true
  image:
    repository: "YOUR_IMAGE_REPOSITORY"
    tag: "0"
  replicaCount: 1
  serviceAccount:
    create: false
  service:
    containerPort: 80


frontend:
  autoscaling:
    enabled: false
  enabled: true
  image:
    repository: ghcr.io/jon-zuka/all/wissen-frontend
    tag: "0.0.0-alpna1"
  replicaCount: 1
  serviceAccount:
    create: false
  service:
    containerPort: 80