name: Publish Package

on:
  push:
    tags:
      - 'v*.*.*' 
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake show
      - run: nix develop --command bun install
      - name: Publish to npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: nix develop --command bun run publish